#
#------------------------------------------

PROGRAM   = gpio_config

# Define files
#------------------------------------------

SRCDIRS   = .
# Define flags
#------------------------------------------
USR_LIB_PATH =../../../../lib/usr_lib
LDFLAGS  = -lar_gpio
CFLAGS    += -I$(USR_LIB_PATH)/ar_gpio/

# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk