# Define target, only one type can be choosed: program, static library or dynamic library.
#------------------------------------------

PROGRAM   = test_mouse_read

# Define files
#------------------------------------------

SRCDIRS   = ./

# Define flags
#------------------------------------------

LDFLAGS   = -lartosyn
CFLAGS    += -I./inc -I../../../../kernel/mods/linux-linaro-stable-lsk-v4.9-17.07/include/

# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk

