#
#------------------------------------------

PROGRAM   = icc_file_operation

# Define files
#------------------------------------------

SRCDIRS   = ./

# Define flags
#------------------------------------------

LDFLAGS   = -lartosyn -lpthread
CFLAGS    += -I./ -ggdb $(KERNEL_EXTRA_CFLAG)

# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk

