#
#------------------------------------------

PROGRAM   = test_icc

# Define files
#------------------------------------------

SRCDIRS   = ./

# Define flags
#------------------------------------------

LDFLAGS   = -lartosyn -lpthread
CFLAGS    += -I./ -ggdb

# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk

