#
#------------------------------------------

#PROGRAM   = xvr_cmd_ui

# Define files
#------------------------------------------

SRCDIRS   = ./
# Define flags
#------------------------------------------
			 
CFLAGS    += 
LOCAL_LIB += 

# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk




