#
#------------------------------------------

DTB   = artosyn-cfg-evb-hdmi-data.dtb artosyn-cfg-smart-usb-data.dtb  artosyn-cfg-data_udp.dtb 
 

# Define files
#------------------------------------------

SRCDIRS   = ./

# Define flags
#------------------------------------------


CFLAGS    += -I$(TOPDIR)/configs/include/dt-bindings/clock \
			 -I$(TOPDIR)/configs/include/dt-bindings/pads \
			 -I$(TOPDIR)/configs/include/dt-bindings/i2s


# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk

