# This is just a redirector file. 
#    The make rules for this directory are found in makefile.mk
#    The generic rules are found in topmake.mk which includes this directory's makefile.mk
include ../../../top.mk
