#
#------------------------------------------

PROGRAM   = pin_share_dump

# Define files
#------------------------------------------

SRCDIRS   = .
# Define flags
#------------------------------------------

# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk
