#
#------------------------------------------

PROGRAM   = test_crypto

# Define files
#------------------------------------------

SRCDIRS   = ./

# Define flags
#------------------------------------------

LDFLAGS   = -lar_crypto -lteec -ltomcrypt -ltommath
CFLAGS    += -I. 

# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk

