#
#------------------------------------------

PROGRAM   = otputil

# Define files
#------------------------------------------

SRCDIRS   = ./

# Define flags
#------------------------------------------
LDFLAGS   +=
CFLAGS    += 

# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk

