# Define target, only one type can be choosed: program, static library or dynamic library.
#------------------------------------------

PROGRAM   = test_spi_ms

# Define files
#------------------------------------------

SRCDIRS   = ./

# Define flags
#------------------------------------------

LDFLAGS   = -lartosyn -lpthread
CFLAGS    += -I./inc

# Include make rule file
#------------------------------------------
include ../../../../makery/usr_app_rule.lmk

