/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ar_dsp_rpc.h"

bool_t
xdr_AR_DSP_IMG_FMT_ID_e (XDR *xdrs, AR_DSP_IMG_FMT_ID_e *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_LOG_LVL_e (XDR *xdrs, AR_DSP_LOG_LVL_e *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_ID_e (XDR *xdrs, AR_DSP_ID_e *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_CDNN_MEMORY_DATA_ORDER_e (XDR *xdrs, AR_CDNN_MEMORY_DATA_ORDER_e *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_CDNN_BUFFER_DATA_TYPE_e (XDR *xdrs, AR_CDNN_BUFFER_DATA_TYPE_e *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_CDNN_BUFFER_BIT_PRECISION_TYPE_e (XDR *xdrs, AR_CDNN_BUFFER_BIT_PRECISION_TYPE_e *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_POINT_st (XDR *xdrs, AR_POINT_st *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_RECT_st (XDR *xdrs, AR_RECT_st *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->x);
			IXDR_PUT_LONG(buf, objp->y);
			IXDR_PUT_LONG(buf, objp->width);
			IXDR_PUT_LONG(buf, objp->height);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
		} else {
			objp->x = IXDR_GET_LONG(buf);
			objp->y = IXDR_GET_LONG(buf);
			objp->width = IXDR_GET_LONG(buf);
			objp->height = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->width))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->height))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_IMG_FMT_st (XDR *xdrs, AR_IMG_FMT_st *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 7 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->channel))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->format))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y_stride))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->u_stride))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->v_stride))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->width);
		IXDR_PUT_LONG(buf, objp->height);
		IXDR_PUT_LONG(buf, objp->channel);
		IXDR_PUT_LONG(buf, objp->format);
		IXDR_PUT_LONG(buf, objp->y_stride);
		IXDR_PUT_LONG(buf, objp->u_stride);
		IXDR_PUT_LONG(buf, objp->v_stride);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->y_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->u_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->v_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->size))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->rgbbuff, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 7 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->channel))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->format))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y_stride))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->u_stride))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->v_stride))
				 return FALSE;

		} else {
		objp->width = IXDR_GET_LONG(buf);
		objp->height = IXDR_GET_LONG(buf);
		objp->channel = IXDR_GET_LONG(buf);
		objp->format = IXDR_GET_LONG(buf);
		objp->y_stride = IXDR_GET_LONG(buf);
		objp->u_stride = IXDR_GET_LONG(buf);
		objp->v_stride = IXDR_GET_LONG(buf);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->y_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->u_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->v_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->size))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->rgbbuff, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->width))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->height))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->channel))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->format))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y_stride))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->u_stride))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v_stride))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->y_addr, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->u_addr, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->v_addr, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->rgbbuff, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ArCdnnOutputBuffer (XDR *xdrs, ArCdnnOutputBuffer *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nchannels))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nInputs))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->width);
		IXDR_PUT_LONG(buf, objp->height);
		IXDR_PUT_LONG(buf, objp->nchannels);
		IXDR_PUT_LONG(buf, objp->nInputs);
		}
		 if (!xdr_vector (xdrs, (char *)objp->buffer_name, 128,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->buffer_size))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->pdata, sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nchannels))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nInputs))
				 return FALSE;

		} else {
		objp->width = IXDR_GET_LONG(buf);
		objp->height = IXDR_GET_LONG(buf);
		objp->nchannels = IXDR_GET_LONG(buf);
		objp->nInputs = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->buffer_name, 128,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->buffer_size))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->pdata, sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->width))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->height))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nchannels))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nInputs))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->buffer_name, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->buffer_size))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->pdata, sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_SOFTMAX_THRD_st (XDR *xdrs, AR_SOFTMAX_THRD_st *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->threshold))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_OUTPUT_st (XDR *xdrs, AR_DSP_OUTPUT_st *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->buffer_num))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->output_buffer, 16,
		sizeof (ArCdnnOutputBuffer), (xdrproc_t) xdr_ArCdnnOutputBuffer))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_STATS_st (XDR *xdrs, AR_DSP_STATS_st *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->cdnn_init_time))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->cdnn_pre_proc_time))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->cdnn_inference_time))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->cdnn_post_proc_time))
				 return FALSE;
		} else {
			IXDR_PUT_U_LONG(buf, objp->cdnn_init_time);
			IXDR_PUT_U_LONG(buf, objp->cdnn_pre_proc_time);
			IXDR_PUT_U_LONG(buf, objp->cdnn_inference_time);
			IXDR_PUT_U_LONG(buf, objp->cdnn_post_proc_time);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->cdnn_init_time))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->cdnn_pre_proc_time))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->cdnn_inference_time))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->cdnn_post_proc_time))
				 return FALSE;
		} else {
			objp->cdnn_init_time = IXDR_GET_U_LONG(buf);
			objp->cdnn_pre_proc_time = IXDR_GET_U_LONG(buf);
			objp->cdnn_inference_time = IXDR_GET_U_LONG(buf);
			objp->cdnn_post_proc_time = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_u_long (xdrs, &objp->cdnn_init_time))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->cdnn_pre_proc_time))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->cdnn_inference_time))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->cdnn_post_proc_time))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_CV_OPS_st (XDR *xdrs, AR_CV_OPS_st *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->cv_ops_bmp))
		 return FALSE;
	 if (!xdr_AR_RECT_st (xdrs, &objp->roi))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->landmark, 64,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ar_callback_func (XDR *xdrs, ar_callback_func *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_ALG_st (XDR *xdrs, AR_DSP_ALG_st *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->dsp_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->alg_type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->exit_code))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->dsp_id);
		IXDR_PUT_LONG(buf, objp->alg_type);
		IXDR_PUT_LONG(buf, objp->exit_code);
		}
		 if (!xdr_vector (xdrs, (char *)objp->input, 4,
			sizeof (AR_IMG_FMT_st), (xdrproc_t) xdr_AR_IMG_FMT_st))
			 return FALSE;
		 if (!xdr_AR_CV_OPS_st (xdrs, &objp->cv_ops))
			 return FALSE;
		 if (!xdr_AR_DSP_OUTPUT_st (xdrs, &objp->output))
			 return FALSE;
		 if (!xdr_AR_DSP_STATS_st (xdrs, &objp->statistics))
			 return FALSE;
		 if (!xdr_ar_callback_func (xdrs, &objp->cb))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->data, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->user_data_pa, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->dsp_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->alg_type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->exit_code))
				 return FALSE;

		} else {
		objp->dsp_id = IXDR_GET_LONG(buf);
		objp->alg_type = IXDR_GET_LONG(buf);
		objp->exit_code = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->input, 4,
			sizeof (AR_IMG_FMT_st), (xdrproc_t) xdr_AR_IMG_FMT_st))
			 return FALSE;
		 if (!xdr_AR_CV_OPS_st (xdrs, &objp->cv_ops))
			 return FALSE;
		 if (!xdr_AR_DSP_OUTPUT_st (xdrs, &objp->output))
			 return FALSE;
		 if (!xdr_AR_DSP_STATS_st (xdrs, &objp->statistics))
			 return FALSE;
		 if (!xdr_ar_callback_func (xdrs, &objp->cb))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->data, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->user_data_pa, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->dsp_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->alg_type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->exit_code))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->input, 4,
		sizeof (AR_IMG_FMT_st), (xdrproc_t) xdr_AR_IMG_FMT_st))
		 return FALSE;
	 if (!xdr_AR_CV_OPS_st (xdrs, &objp->cv_ops))
		 return FALSE;
	 if (!xdr_AR_DSP_OUTPUT_st (xdrs, &objp->output))
		 return FALSE;
	 if (!xdr_AR_DSP_STATS_st (xdrs, &objp->statistics))
		 return FALSE;
	 if (!xdr_ar_callback_func (xdrs, &objp->cb))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->data, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->user_data_pa, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_CDNN_INPUT_PARAMS_st (XDR *xdrs, AR_CDNN_INPUT_PARAMS_st *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataType))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->depth))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->nChannels))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->width);
		IXDR_PUT_U_LONG(buf, objp->height);
		IXDR_PUT_U_LONG(buf, objp->dataType);
		IXDR_PUT_U_LONG(buf, objp->depth);
		IXDR_PUT_U_LONG(buf, objp->nChannels);
		}
		 if (!xdr_float (xdrs, &objp->scaleFactor))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (4 + ( 4 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dataOrder))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->nInputs))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataFlipped))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataTransposed))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->padding, 4,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dataOrder);
		IXDR_PUT_U_LONG(buf, objp->nInputs);
		IXDR_PUT_U_LONG(buf, objp->dataFlipped);
		IXDR_PUT_U_LONG(buf, objp->dataTransposed);
		{
			register int *genp;

			for (i = 0, genp = objp->padding;
				i < 4; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		}
		 if (!xdr_vector (xdrs, (char *)objp->pLayerName, 32,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->bufferId))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataType))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->depth))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->nChannels))
				 return FALSE;

		} else {
		objp->width = IXDR_GET_U_LONG(buf);
		objp->height = IXDR_GET_U_LONG(buf);
		objp->dataType = IXDR_GET_U_LONG(buf);
		objp->depth = IXDR_GET_U_LONG(buf);
		objp->nChannels = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_float (xdrs, &objp->scaleFactor))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (4 + ( 4 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dataOrder))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->nInputs))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataFlipped))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataTransposed))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->padding, 4,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		objp->dataOrder = IXDR_GET_U_LONG(buf);
		objp->nInputs = IXDR_GET_U_LONG(buf);
		objp->dataFlipped = IXDR_GET_U_LONG(buf);
		objp->dataTransposed = IXDR_GET_U_LONG(buf);
		{
			register int *genp;

			for (i = 0, genp = objp->padding;
				i < 4; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		}
		 if (!xdr_vector (xdrs, (char *)objp->pLayerName, 32,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->bufferId))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->width))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->height))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataType))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->depth))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->nChannels))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->scaleFactor))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataOrder))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->nInputs))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataFlipped))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataTransposed))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->padding, 4,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pLayerName, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->bufferId))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_USR_CFG_st (XDR *xdrs, AR_DSP_USR_CFG_st *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->operation_id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->params, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_CNN_CFG_st (XDR *xdrs, AR_DSP_CNN_CFG_st *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 15 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->network_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->network_type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->do_debug_logging))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->do_profiling))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->channel_swap))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->raw_scale))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->bw_reduction))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->resize_input))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->amend_flag))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->block_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->block_number))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->block_interval))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num_of_inference))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max_width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max_height))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->network_id);
		IXDR_PUT_LONG(buf, objp->network_type);
		IXDR_PUT_LONG(buf, objp->do_debug_logging);
		IXDR_PUT_LONG(buf, objp->do_profiling);
		IXDR_PUT_LONG(buf, objp->channel_swap);
		IXDR_PUT_LONG(buf, objp->raw_scale);
		IXDR_PUT_LONG(buf, objp->bw_reduction);
		IXDR_PUT_LONG(buf, objp->resize_input);
		IXDR_PUT_LONG(buf, objp->amend_flag);
		IXDR_PUT_LONG(buf, objp->block_size);
		IXDR_PUT_LONG(buf, objp->block_number);
		IXDR_PUT_LONG(buf, objp->block_interval);
		IXDR_PUT_LONG(buf, objp->num_of_inference);
		IXDR_PUT_LONG(buf, objp->max_width);
		IXDR_PUT_LONG(buf, objp->max_height);
		}
		 if (!xdr_float (xdrs, &objp->bw_reduction_ratio))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (1 + ( 4  + 4  + 4 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->num_inputs))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->input_format, 4,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->input_buf_len, 4,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->input_buf, 4,
				sizeof (u_long), (xdrproc_t) xdr_u_long))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->num_inputs);
		{
			register int *genp;

			for (i = 0, genp = objp->input_format;
				i < 4; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		{
			register int *genp;

			for (i = 0, genp = objp->input_buf_len;
				i < 4; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		{
			register u_long *genp;

			for (i = 0, genp = objp->input_buf;
				i < 4; ++i) {
				IXDR_PUT_U_LONG(buf, *genp++);
			}
		}
		}
		 if (!xdr_vector (xdrs, (char *)objp->input_params, 4,
			sizeof (AR_CDNN_INPUT_PARAMS_st), (xdrproc_t) xdr_AR_CDNN_INPUT_PARAMS_st))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->output_threshold))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->weight_file_path, 128,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->file_len))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->load_addr))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->len_of_buffer_for_pdata))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->buffer_pa_for_pdata))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->buffer_va_for_pdata))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->file_len);
		IXDR_PUT_U_LONG(buf, objp->load_addr);
		IXDR_PUT_LONG(buf, objp->len_of_buffer_for_pdata);
		IXDR_PUT_U_LONG(buf, objp->buffer_pa_for_pdata);
		IXDR_PUT_U_LONG(buf, objp->buffer_va_for_pdata);
		}
		 if (!xdr_vector (xdrs, (char *)objp->softmax_thrd, 8,
			sizeof (AR_SOFTMAX_THRD_st), (xdrproc_t) xdr_AR_SOFTMAX_THRD_st))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->resize_by_dsp))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->other_parameters, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 15 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->network_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->network_type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->do_debug_logging))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->do_profiling))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->channel_swap))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->raw_scale))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->bw_reduction))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->resize_input))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->amend_flag))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->block_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->block_number))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->block_interval))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num_of_inference))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max_width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max_height))
				 return FALSE;

		} else {
		objp->network_id = IXDR_GET_LONG(buf);
		objp->network_type = IXDR_GET_LONG(buf);
		objp->do_debug_logging = IXDR_GET_LONG(buf);
		objp->do_profiling = IXDR_GET_LONG(buf);
		objp->channel_swap = IXDR_GET_LONG(buf);
		objp->raw_scale = IXDR_GET_LONG(buf);
		objp->bw_reduction = IXDR_GET_LONG(buf);
		objp->resize_input = IXDR_GET_LONG(buf);
		objp->amend_flag = IXDR_GET_LONG(buf);
		objp->block_size = IXDR_GET_LONG(buf);
		objp->block_number = IXDR_GET_LONG(buf);
		objp->block_interval = IXDR_GET_LONG(buf);
		objp->num_of_inference = IXDR_GET_LONG(buf);
		objp->max_width = IXDR_GET_LONG(buf);
		objp->max_height = IXDR_GET_LONG(buf);
		}
		 if (!xdr_float (xdrs, &objp->bw_reduction_ratio))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (1 + ( 4  + 4  + 4 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->num_inputs))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->input_format, 4,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->input_buf_len, 4,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->input_buf, 4,
				sizeof (u_long), (xdrproc_t) xdr_u_long))
				 return FALSE;

		} else {
		objp->num_inputs = IXDR_GET_LONG(buf);
		{
			register int *genp;

			for (i = 0, genp = objp->input_format;
				i < 4; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		{
			register int *genp;

			for (i = 0, genp = objp->input_buf_len;
				i < 4; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		{
			register u_long *genp;

			for (i = 0, genp = objp->input_buf;
				i < 4; ++i) {
				*genp++ = IXDR_GET_U_LONG(buf);
			}
		}
		}
		 if (!xdr_vector (xdrs, (char *)objp->input_params, 4,
			sizeof (AR_CDNN_INPUT_PARAMS_st), (xdrproc_t) xdr_AR_CDNN_INPUT_PARAMS_st))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->output_threshold))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->weight_file_path, 128,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->file_len))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->load_addr))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->len_of_buffer_for_pdata))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->buffer_pa_for_pdata))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->buffer_va_for_pdata))
				 return FALSE;

		} else {
		objp->file_len = IXDR_GET_U_LONG(buf);
		objp->load_addr = IXDR_GET_U_LONG(buf);
		objp->len_of_buffer_for_pdata = IXDR_GET_LONG(buf);
		objp->buffer_pa_for_pdata = IXDR_GET_U_LONG(buf);
		objp->buffer_va_for_pdata = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->softmax_thrd, 8,
			sizeof (AR_SOFTMAX_THRD_st), (xdrproc_t) xdr_AR_SOFTMAX_THRD_st))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->resize_by_dsp))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->other_parameters, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->network_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->network_type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->do_debug_logging))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->do_profiling))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->channel_swap))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->raw_scale))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bw_reduction))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->resize_input))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->amend_flag))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->block_size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->block_number))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->block_interval))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_of_inference))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max_width))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max_height))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->bw_reduction_ratio))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_inputs))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->input_format, 4,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->input_buf_len, 4,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->input_buf, 4,
		sizeof (u_long), (xdrproc_t) xdr_u_long))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->input_params, 4,
		sizeof (AR_CDNN_INPUT_PARAMS_st), (xdrproc_t) xdr_AR_CDNN_INPUT_PARAMS_st))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->output_threshold))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->weight_file_path, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->file_len))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->load_addr))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->len_of_buffer_for_pdata))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->buffer_pa_for_pdata))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->buffer_va_for_pdata))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->softmax_thrd, 8,
		sizeof (AR_SOFTMAX_THRD_st), (xdrproc_t) xdr_AR_SOFTMAX_THRD_st))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->resize_by_dsp))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->other_parameters, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_CFG_st (XDR *xdrs, AR_DSP_CFG_st *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->cdnn_sram_heap_start))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cdnn_sram_heap_size))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->cdnn_ext_mem_addr))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cdnn_ext_mem_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dsp_log_level))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->reserved))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->cdnn_sram_heap_start);
		IXDR_PUT_LONG(buf, objp->cdnn_sram_heap_size);
		IXDR_PUT_U_LONG(buf, objp->cdnn_ext_mem_addr);
		IXDR_PUT_LONG(buf, objp->cdnn_ext_mem_size);
		IXDR_PUT_LONG(buf, objp->dsp_log_level);
		IXDR_PUT_LONG(buf, objp->reserved);
		}
		 if (!xdr_vector (xdrs, (char *)objp->cnn_cfg, 16,
			sizeof (AR_DSP_CNN_CFG_st), (xdrproc_t) xdr_AR_DSP_CNN_CFG_st))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->user_cfg, 16,
			sizeof (AR_DSP_USR_CFG_st), (xdrproc_t) xdr_AR_DSP_USR_CFG_st))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->cdnn_sram_heap_start))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cdnn_sram_heap_size))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->cdnn_ext_mem_addr))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cdnn_ext_mem_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dsp_log_level))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->reserved))
				 return FALSE;

		} else {
		objp->cdnn_sram_heap_start = IXDR_GET_U_LONG(buf);
		objp->cdnn_sram_heap_size = IXDR_GET_LONG(buf);
		objp->cdnn_ext_mem_addr = IXDR_GET_U_LONG(buf);
		objp->cdnn_ext_mem_size = IXDR_GET_LONG(buf);
		objp->dsp_log_level = IXDR_GET_LONG(buf);
		objp->reserved = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->cnn_cfg, 16,
			sizeof (AR_DSP_CNN_CFG_st), (xdrproc_t) xdr_AR_DSP_CNN_CFG_st))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->user_cfg, 16,
			sizeof (AR_DSP_USR_CFG_st), (xdrproc_t) xdr_AR_DSP_USR_CFG_st))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_long (xdrs, &objp->cdnn_sram_heap_start))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cdnn_sram_heap_size))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->cdnn_ext_mem_addr))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cdnn_ext_mem_size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dsp_log_level))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->reserved))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->cnn_cfg, 16,
		sizeof (AR_DSP_CNN_CFG_st), (xdrproc_t) xdr_AR_DSP_CNN_CFG_st))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->user_cfg, 16,
		sizeof (AR_DSP_USR_CFG_st), (xdrproc_t) xdr_AR_DSP_USR_CFG_st))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_CFG_RPC_st (XDR *xdrs, AR_DSP_CFG_RPC_st *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dsp_id))
		 return FALSE;
	 if (!xdr_AR_DSP_CFG_st (xdrs, &objp->dsp_cfg_st))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_IMG_FMT_RPC_st (XDR *xdrs, AR_IMG_FMT_RPC_st *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 7 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->channel))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->format))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y_stride))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->u_stride))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->v_stride))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->width);
		IXDR_PUT_LONG(buf, objp->height);
		IXDR_PUT_LONG(buf, objp->channel);
		IXDR_PUT_LONG(buf, objp->format);
		IXDR_PUT_LONG(buf, objp->y_stride);
		IXDR_PUT_LONG(buf, objp->u_stride);
		IXDR_PUT_LONG(buf, objp->v_stride);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->y_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->u_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->v_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->size))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->rgbbuff, MAX_INPUT_IMG_BUF_SIZE,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 7 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->channel))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->format))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y_stride))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->u_stride))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->v_stride))
				 return FALSE;

		} else {
		objp->width = IXDR_GET_LONG(buf);
		objp->height = IXDR_GET_LONG(buf);
		objp->channel = IXDR_GET_LONG(buf);
		objp->format = IXDR_GET_LONG(buf);
		objp->y_stride = IXDR_GET_LONG(buf);
		objp->u_stride = IXDR_GET_LONG(buf);
		objp->v_stride = IXDR_GET_LONG(buf);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->y_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->u_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->v_addr, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->size))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->rgbbuff, MAX_INPUT_IMG_BUF_SIZE,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->width))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->height))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->channel))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->format))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y_stride))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->u_stride))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v_stride))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->y_addr, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->u_addr, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->v_addr, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rgbbuff, MAX_INPUT_IMG_BUF_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ArCdnnOutputBuffer_RPC_st (XDR *xdrs, ArCdnnOutputBuffer_RPC_st *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nchannels))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nInputs))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->width);
		IXDR_PUT_LONG(buf, objp->height);
		IXDR_PUT_LONG(buf, objp->nchannels);
		IXDR_PUT_LONG(buf, objp->nInputs);
		}
		 if (!xdr_vector (xdrs, (char *)objp->buffer_name, 128,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->buffer_size))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->pdata, MAX_OUTPUT_PDATA_SIZE,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nchannels))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nInputs))
				 return FALSE;

		} else {
		objp->width = IXDR_GET_LONG(buf);
		objp->height = IXDR_GET_LONG(buf);
		objp->nchannels = IXDR_GET_LONG(buf);
		objp->nInputs = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->buffer_name, 128,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->buffer_size))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->pdata, MAX_OUTPUT_PDATA_SIZE,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->width))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->height))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nchannels))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nInputs))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->buffer_name, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->buffer_size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pdata, MAX_OUTPUT_PDATA_SIZE,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_OUTPUT_RPC_st (XDR *xdrs, AR_DSP_OUTPUT_RPC_st *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->buffer_num))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->output_buffer, 16,
		sizeof (ArCdnnOutputBuffer_RPC_st), (xdrproc_t) xdr_ArCdnnOutputBuffer_RPC_st))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_ALG_RPC_IN_st (XDR *xdrs, AR_DSP_ALG_RPC_IN_st *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->dsp_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->alg_type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->exit_code))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->dsp_id);
		IXDR_PUT_LONG(buf, objp->alg_type);
		IXDR_PUT_LONG(buf, objp->exit_code);
		}
		 if (!xdr_vector (xdrs, (char *)objp->input, 4,
			sizeof (AR_IMG_FMT_RPC_st), (xdrproc_t) xdr_AR_IMG_FMT_RPC_st))
			 return FALSE;
		 if (!xdr_AR_CV_OPS_st (xdrs, &objp->cv_ops))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->dsp_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->alg_type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->exit_code))
				 return FALSE;

		} else {
		objp->dsp_id = IXDR_GET_LONG(buf);
		objp->alg_type = IXDR_GET_LONG(buf);
		objp->exit_code = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->input, 4,
			sizeof (AR_IMG_FMT_RPC_st), (xdrproc_t) xdr_AR_IMG_FMT_RPC_st))
			 return FALSE;
		 if (!xdr_AR_CV_OPS_st (xdrs, &objp->cv_ops))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->dsp_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->alg_type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->exit_code))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->input, 4,
		sizeof (AR_IMG_FMT_RPC_st), (xdrproc_t) xdr_AR_IMG_FMT_RPC_st))
		 return FALSE;
	 if (!xdr_AR_CV_OPS_st (xdrs, &objp->cv_ops))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_ALG_RPC_OUT_st (XDR *xdrs, AR_DSP_ALG_RPC_OUT_st *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->dsp_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->alg_type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->exit_code))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->dsp_id);
		IXDR_PUT_LONG(buf, objp->alg_type);
		IXDR_PUT_LONG(buf, objp->exit_code);
		}
		 if (!xdr_AR_DSP_OUTPUT_RPC_st (xdrs, &objp->output))
			 return FALSE;
		 if (!xdr_AR_DSP_STATS_st (xdrs, &objp->statistics))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->dsp_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->alg_type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->exit_code))
				 return FALSE;

		} else {
		objp->dsp_id = IXDR_GET_LONG(buf);
		objp->alg_type = IXDR_GET_LONG(buf);
		objp->exit_code = IXDR_GET_LONG(buf);
		}
		 if (!xdr_AR_DSP_OUTPUT_RPC_st (xdrs, &objp->output))
			 return FALSE;
		 if (!xdr_AR_DSP_STATS_st (xdrs, &objp->statistics))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->dsp_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->alg_type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->exit_code))
		 return FALSE;
	 if (!xdr_AR_DSP_OUTPUT_RPC_st (xdrs, &objp->output))
		 return FALSE;
	 if (!xdr_AR_DSP_STATS_st (xdrs, &objp->statistics))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_DSP_ALG_TO_RPC_IN_st (XDR *xdrs, AR_DSP_ALG_TO_RPC_IN_st *objp)
{
	register int32_t *buf;

	 if (!xdr_AR_DSP_ALG_RPC_IN_st (xdrs, &objp->ar_alg_rpc_st))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->timeout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AR_FILE_CHUNK_st (XDR *xdrs, AR_FILE_CHUNK_st *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, FILE_CHUNK_DATA_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->chunk_bytes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->total_len))
		 return FALSE;
	return TRUE;
}
